// AUTH
export const SET_AUTH = 'SET_AUTH'

// LOADING
export const SET_LOADING_PENDING = 'SET_LOADING_PENDING'


// MODAL
export const SET_MODAL_OPEN = 'SET_MODAL_OPEN'
export const SET_MODAL_NAME = 'SET_MODAL_NAME'